# fly.toml app configuration file generated for pickup-morning-butterfly-214-empty-dust-9909 on 2024-03-07T00:12:59-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pickup-morning-butterfly-214-empty-dust-9909'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
